server:
  port: 5052
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: root
  #  zipkin:
  #    enabled: true
  #    base-url: http://localhost:9411
  #    service:
  #      name: auth-service
  data:
    mongodb:
      host: localhost
      port: 27020
      username: movieappuser
      password: 12345
      database: movieapp
      uri: mongodb://movieappuser:12345@localhost:27020/movieapp
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#  security:
#    user:
#      name: kullanici
#      password: 12345

